### ISSUE TITLE
Colors are off compared to Vercel's theme

### ISSUE THREAD

**Issue by oasaleh** [triyanox/vercel-theme#2] opened 2023-11-15 13:40 UTC
this theme
<img width="424" alt="image" src="https://github.com/triyanox/vercel-theme/assets/56449814/6a234a3c-8cd4-4051-8b3e-cf5053500621">

Original theme by Vercel
<img width="484" alt="image" src="https://github.com/triyanox/vercel-theme/assets/56449814/28ff6047-f0b1-4d9a-b61e-5d57a9269693">

The green is a bit off.. `Response`, `$token`, `Request`, `CookieStore` and curly brackets are in different colors

**Comment by chaqchase** [comment] 2023-12-18 14:52
@oasaleh Thank you for opening this issue ! The issue is fixed on v1.0.3 but some small differences for better accessbility.

**Closed as completed by chaqchase** 2023-12-18 14:52 UTC
