### ISSUE TITLE
File names not visible when searching with vscode shortcut

### ISSUE THREAD

**Issue by vitoorgomes** [triyanox/vercel-theme#1] opened 2022-12-15 20:10 UTC
When using VS Search tool (cmd + p) and typing the file name, because of the background color and text color are the same, it's not visible.

For few files, it's ok, but when many files have similar name, it causes some confusion
![SCR-20221215-nmj](https://user-images.githubusercontent.com/41302394/207956903-d967072e-97be-411a-bf0c-c91874969efb.png)
![SCR-20221215-nmn](https://user-images.githubusercontent.com/41302394/207956908-eec5a70f-625b-4cd2-9f7c-a2d49a683a48.png)

Along side with this issue, is it possible to have some contrast between then opened file and the rest of the vscode thinks like the toolbar, explorer tree, bottom bar and so on?

**Comment by chaqchase** [comment] 2022-12-27 14:35
Thank you so much for opening this issue ! I will work on it on the next version of the theme also it gona include multiple variants .

**Comment by chaqchase** [comment] 2023-12-18 14:54
@vitoorgomes Thank you so much for opening this issue ! The issue is fixed on v1.0.3 !

**Closed as completed by chaqchase** 2023-12-18 14:54 UTC
